import type { ReactElement } from 'react';
import Head from 'next/head';

import LoginForm from '../components/Forms/LoginForm';
import Dashboard from '../components/Layout/Dashboard';
import styles from '../styles/Login.module.css';

const Page = () => {
  return (
    <div className={styles.all}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.authContainer}>
        <LoginForm />
      </div>
    </div>
  );
};

export default Page;
